package cardealersystem;


import Admin.Dashboard;
import Dealers.Dealer_Dashboard;
import config.dbConnector;
import config.pasHasher;
import config.session;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
   static String status;
   static String type;
   
   public static boolean loginAcc(String username, String password){
    dbConnector connector = new dbConnector();
 
    try {
        String query = "SELECT * FROM tbl_users WHERE u_username = '" + username + "'";
        ResultSet resultSet = connector.getData(query);
        if(resultSet.next()){
                       
                String hashedPass = resultSet.getString("u_password");
                String rehashedPass = pasHasher.hashPassword(password);
                
                if(hashedPass.equals(rehashedPass)){
                     status = resultSet.getString("u_status");
                     type = resultSet.getString("u_type");
                     session ses = session.getInstance();
                     ses.setId(resultSet.getInt("u_id"));
                     ses.setFn(resultSet.getString("u_fname"));
                     ses.setLn(resultSet.getString("u_lname"));
                     ses.setEm(resultSet.getString("u_email"));
                     ses.setCt(resultSet.getString("u_contact"));
                     ses.setUn(resultSet.getString("u_username"));
                     ses.setTacc(resultSet.getString("u_type"));
                     ses.setStat(resultSet.getString("u_status"));
                    
                     return true;                              
                }else{
                   return false;
               }                        
        }else{
            System.out.println("Password isnt Match!");
            return false;
        }
    } catch (SQLException |NoSuchAlgorithmException ex) {
        System.out.println(""+ex);
        return false;
    }
}

            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LoginI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 17, 23));
        jPanel1.setForeground(new java.awt.Color(65, 67, 106));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 320, 50));

        jLabel6.setBackground(new java.awt.Color(201, 209, 217));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 209, 217));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USERNAME:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(201, 209, 217));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PASSWORD:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 170, 50));

        LoginI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LoginI.setText("LOGIN");
        LoginI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginIActionPerformed(evt);
            }
        });
        jPanel1.add(LoginI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 100, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 209, 217));
        jLabel2.setText("Not yet registered?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 200, 30));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 320, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(191, 174, 112));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DriveLine Hub");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 70, 500, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 170));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Forget Password");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginIActionPerformed
      if (password.getText().isEmpty() || username.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "All Fields are Required");
            Login lf = new Login();
            lf.setVisible(true);
            this.dispose();            
        }else if (loginAcc(username.getText(), password.getText())) {

            if (!status.equals("Active")) {
                JOptionPane.showMessageDialog(null, "Inactive Account. Contact Admin at 09289873493");
            }else {
                session ses = session.getInstance(); 
                String logMessage = "User Login: " + ses.getUn();
                String timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

                try {
                    dbConnector dbc = new dbConnector();
                    String logSql = "INSERT INTO tbl_logs (u_id, actions, date) VALUES (?, ?, ?)";
                    PreparedStatement logStmt = dbc.getConnection().prepareStatement(logSql);
                    logStmt.setInt(1, ses.getId()); 
                    logStmt.setString(2, logMessage);
                    logStmt.setString(3, timestamp);
                    logStmt.executeUpdate();
                    logStmt.close();
                }catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Failed to write login log.");
                }

                JOptionPane.showMessageDialog(null, "Login Success!");
                if (type.equals("Admin")) {
                    Dashboard ads = new Dashboard();
                    ads.setVisible(true);
                    this.dispose();
                } else if (type.equals("Dealer")) {
                    Dealer_Dashboard ddb = new Dealer_Dashboard();
                    ddb.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No Account Type Found, Contact Admin");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Login Failed");
            
      }
    }//GEN-LAST:event_LoginIActionPerformed
  
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        RegisterForm rtf = new RegisterForm();
        rtf.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ForgetPassword fp = new ForgetPassword();
        fp.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
      if (password.getEchoChar() == (char) 0) {  
            password.setEchoChar('*'); 
        } else {  
            password.setEchoChar((char) 0);
        }      }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
