package Admin;

import cardealersystem.Login;
import cardealersystem.RegisterForm;
import config.session;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
        Color colorenter = new Color (13,16,23);
        Color colorexit = new Color (65,110,129);
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_user = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Uaname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Uid = new javax.swing.JLabel();
        Udname3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acc_edit = new javax.swing.JPanel();
        Edit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Logs = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        print3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        add_user.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 17, 23));
        jPanel1.setForeground(new java.awt.Color(65, 67, 106));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(191, 174, 112));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 270, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 209, 217));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEALERS");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 230, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personnel-icon.png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 240, 210);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 270, 280));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(201, 209, 217));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 110, 70));

        Uaname.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Uaname.setForeground(new java.awt.Color(201, 209, 217));
        Uaname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Uaname.setText("ADMIN ");
        jPanel1.add(Uaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 140));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(191, 174, 112));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DriveLine Hub");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 350, 60));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images (1).png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 20, 220, 200);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(201, 209, 217));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CARS");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(80, 230, 110, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 260, 280));

        Uid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Uid.setForeground(new java.awt.Color(201, 209, 217));
        Uid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Uid.setText("ID");
        jPanel1.add(Uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 160, 50));

        Udname3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Udname3.setForeground(new java.awt.Color(201, 209, 217));
        Udname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Udname3.setText("ADMIN ID:");
        jPanel1.add(Udname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 50));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(191, 174, 112));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 400, 60));

        acc_edit.setBackground(new java.awt.Color(65, 110, 129));
        acc_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acc_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acc_editMouseExited(evt);
            }
        });
        acc_edit.setLayout(null);

        Edit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Edit.setForeground(new java.awt.Color(201, 209, 217));
        Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edit.setText("SETTINGS");
        acc_edit.add(Edit);
        Edit.setBounds(30, 20, 130, 20);

        jPanel1.add(acc_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 60));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(201, 209, 217));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DEALS");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(80, 230, 110, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/briefcase2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 20, 220, 200);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 260, 280));

        Logs.setBackground(new java.awt.Color(65, 110, 129));
        Logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogsMouseExited(evt);
            }
        });
        Logs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(201, 209, 217));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(201, 209, 217));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LOGS");
        Logs.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 20));

        print3.setBackground(new java.awt.Color(65, 110, 129));
        print3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print3MouseExited(evt);
            }
        });
        print3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(201, 209, 217));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(201, 209, 217));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PRINT");
        print3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 20));

        Logs.add(print3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 250, 60));

        jPanel1.add(Logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        User_Dashboard udb = new User_Dashboard();
        udb.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        session ses = session.getInstance();
        
        if(ses.getId()== 0){
        JOptionPane.showMessageDialog(null, "Login First");
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
        }
        Uaname.setText(""+ses.getUn());
        Uid.setText(""+ses.getId());
    }//GEN-LAST:event_formWindowActivated

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        CarDashbroad cdb = new CarDashbroad();
        cdb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void acc_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_editMouseClicked
        AdminInfo ai = new AdminInfo();
        ai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acc_editMouseClicked

    private void acc_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_editMouseEntered
        acc_edit.setBackground(colorenter);
    }//GEN-LAST:event_acc_editMouseEntered

    private void acc_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_editMouseExited
        acc_edit.setBackground(colorexit);
    }//GEN-LAST:event_acc_editMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        DealsStatus dss = new DealsStatus();
        dss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void print3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print3MouseClicked

    private void print3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print3MouseEntered
        Logs.setBackground(colorenter);
    }//GEN-LAST:event_print3MouseEntered

    private void print3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print3MouseExited

    }//GEN-LAST:event_print3MouseExited

    private void LogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseClicked
        Logs lgs = new Logs();
        lgs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogsMouseClicked

    private void LogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseEntered
        Logs.setBackground(colorenter);
    }//GEN-LAST:event_LogsMouseEntered

    private void LogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseExited
        Logs.setBackground(colorexit);
    }//GEN-LAST:event_LogsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edit;
    private javax.swing.JPanel Logs;
    private javax.swing.JLabel Uaname;
    private javax.swing.JLabel Udname3;
    private javax.swing.JLabel Uid;
    private javax.swing.JPanel acc_edit;
    private javax.swing.JPanel add_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel print3;
    // End of variables declaration//GEN-END:variables
}
